experiment_name: googlenet for cub200
experiment_type: loc
experiment_extr: hma-cs
experiment_type: train

dataset:
  name: cub200  # ilsvrc
  root: /data/CUB-200-2011    
  crop: RandomResizedCrop   

network:
  name: googlenetbn
  img_size: 224
  cam_size: 14
  out_size: 200

train:
  epoch_sp: 0
  epoch_ep: 45  
  batch_size: 256
  device_ids: [0,1]
  worker_num: 4
  params_path: /home/bowang/.torch/googlenet-1378be20.pth
  resume_path: 

test:
  batch_size: 1
  device_ids: [0]
  img_scales: [224, 336, 448]
  cam_segthd: 0.2
  params_path: /home/bowang/code-mypaper-gpl/wsol-mLDFR-2020/logs/loc-googlenetbn-cub200-b256-f14-sgd-max-hma-cs-202102031206/20210115-09-14-41.pth
  locbox_root: results/loc-googlenetbn-cub200-b256-f14-sgd-max-hma-cs-202102031206-41-s02-224-336-448.box
  scores_file: results/loc-googlenetbn-cub200-b256-f14-sgd-max-hma-cs-202102031206-41.preds
  corloc_file: results/loc-googlenetbn-cub200-b256-f14-sgd-max-hma-cs-202102031206-41-s02-224-336-448.corloc_box
  clsloc_file: results/loc-googlenetbn-cub200-b256-f14-sgd-max-hma-cs-202102031206-41-s02-224-336-448.clsloc_box
  visual_root: results/loc-googlenetbn-cub200-b256-f14-sgd-max-hma-cs-202102031206-41-s02-224-336-448.vis  